export const ROLES = {
  HOST: "HOST",
  CO_HOST: "CO-HOST",
  SPEAKER: "SPEAKER",
  LISTENER: "LISTENER",
};

export const TYPE_ACTION = {
  MUTE_ALL: "MUTE_ALL",
  UN_MUTE_ALL: "UN_MUTE_ALL",
  REQUEST_TO_SPEAKER: "REQUEST_TO_SPEAKER",
  ACCEPT_TO_SPEAKER: "ACCEPT_TO_SPEAKER",
  REJECT_TO_SPEAKER: "REJECT_TO_SPEAKER",
  MUTE_USER: "MUTE_USER",
  TOGGLE_MUTE_SELF: "TOGGLE_MUTE_SELF",
  UPDATE_ATTRIBUTES: "UPDATE_ATTRIBUTES",
  UPDATE_ROLE_USER: "UPDATE_ROLE_USER",
};
